GET http://localhost:8090/price/matic
###

GET http://localhost:8090/
###

GET http://localhost:8090/stoploss/nfts/0x395977E98105A96328357f847Edc75333015b8f4

###

GET http://localhost:8090/stoploss/userTrades/1&[0]

###

GET http://localhost:8090/stoploss/openOrders

###

GET http://localhost:8090/stoploss/settings

###

GET http://localhost:8090/limit/openOrders

###

GET http://localhost:8090/limit/vaults/0x395977E98105A96328357f847Edc75333015b8f4

###

GET http://localhost:8090/limit/trades/1
###

GET http://localhost:8090/stop/openOrders

###
GET http://localhost:8090/stop/vaults/0x395977E98105A96328357f847Edc75333015b8f4

###

GET http://localhost:8090/stop/trades/17

###
GET http://localhost:8090/accumulatordistributor/vaults/0x395977E98105A96328357f847Edc75333015b8f4
###

GET http://localhost:8090/accumulatordistributor/openOrders

###

GET http://localhost:8090/chef/poolData

###

GET http://localhost:8090/chef/userPoolData/0x395977E98105A96328357f847Edc75333015b8f4
