GET http://localhost:8090/price/matic
###

GET http://localhost:8090/
###

GET http://localhost:8090/stoploss/nfts/0x395977E98105A96328357f847Edc75333015b8f4

###

GET http://localhost:8090/stoploss/userTrades/1&[0]